// Generated by server/eval/clip_index.py - do not edit by hand.
window.CLIPS = [
 {
  "en": "The patient, myself",
  "hi": "मरीज़ ख़ुद",
  "used_by": [
   "identity.respondent=self"
  ],
  "asked": [
   {
    "qid": "identity.respondent",
    "en": "Who is answering these questions?",
    "hi": "इन सवालों का जवाब कौन दे रहा है?"
   }
  ],
  "index": "001",
  "roman": "mareez khud"
 },
 {
  "en": "A family member",
  "hi": "परिवार का सदस्य",
  "used_by": [
   "identity.respondent=relative"
  ],
  "asked": [
   {
    "qid": "identity.respondent",
    "en": "Who is answering these questions?",
    "hi": "इन सवालों का जवाब कौन दे रहा है?"
   }
  ],
  "index": "002",
  "roman": "parivaar ka sadasya"
 },
 {
  "en": "Someone helping them",
  "hi": "साथ आया कोई व्यक्ति",
  "used_by": [
   "identity.respondent=attendant"
  ],
  "asked": [
   {
    "qid": "identity.respondent",
    "en": "Who is answering these questions?",
    "hi": "इन सवालों का जवाब कौन दे रहा है?"
   }
  ],
  "index": "003",
  "roman": "saath aaya koi vyakti"
 },
 {
  "en": "Under 18",
  "hi": "18 से कम",
  "used_by": [
   "identity.age_band=under_18"
  ],
  "asked": [
   {
    "qid": "identity.age_band",
    "en": "How old is the patient?",
    "hi": "मरीज़ की उम्र कितनी है?"
   }
  ],
  "index": "004",
  "roman": "18 se kam"
 },
 {
  "en": "18 to 39",
  "hi": "18 से 39",
  "used_by": [
   "identity.age_band=18_39"
  ],
  "asked": [
   {
    "qid": "identity.age_band",
    "en": "How old is the patient?",
    "hi": "मरीज़ की उम्र कितनी है?"
   }
  ],
  "index": "005",
  "roman": "18 se 39"
 },
 {
  "en": "40 to 59",
  "hi": "40 से 59",
  "used_by": [
   "identity.age_band=40_59"
  ],
  "asked": [
   {
    "qid": "identity.age_band",
    "en": "How old is the patient?",
    "hi": "मरीज़ की उम्र कितनी है?"
   }
  ],
  "index": "006",
  "roman": "40 se 59"
 },
 {
  "en": "60 to 74",
  "hi": "60 से 74",
  "used_by": [
   "identity.age_band=60_74"
  ],
  "asked": [
   {
    "qid": "identity.age_band",
    "en": "How old is the patient?",
    "hi": "मरीज़ की उम्र कितनी है?"
   }
  ],
  "index": "007",
  "roman": "60 se 74"
 },
 {
  "en": "75 or older",
  "hi": "75 या उससे ज़्यादा",
  "used_by": [
   "identity.age_band=75_plus"
  ],
  "asked": [
   {
    "qid": "identity.age_band",
    "en": "How old is the patient?",
    "hi": "मरीज़ की उम्र कितनी है?"
   }
  ],
  "index": "008",
  "roman": "75 ya usse zyada"
 },
 {
  "en": "Female",
  "hi": "महिला",
  "used_by": [
   "identity.sex=female"
  ],
  "asked": [
   {
    "qid": "identity.sex",
    "en": "Is the patient male or female?",
    "hi": "मरीज़ पुरुष हैं या महिला?"
   }
  ],
  "index": "009",
  "roman": "mahila"
 },
 {
  "en": "Male",
  "hi": "पुरुष",
  "used_by": [
   "identity.sex=male"
  ],
  "asked": [
   {
    "qid": "identity.sex",
    "en": "Is the patient male or female?",
    "hi": "मरीज़ पुरुष हैं या महिला?"
   }
  ],
  "index": "010",
  "roman": "purush"
 },
 {
  "en": "Other",
  "hi": "अन्य",
  "used_by": [
   "identity.sex=other"
  ],
  "asked": [
   {
    "qid": "identity.sex",
    "en": "Is the patient male or female?",
    "hi": "मरीज़ पुरुष हैं या महिला?"
   }
  ],
  "index": "011",
  "roman": "anya"
 },
 {
  "en": "Prefer not to say",
  "hi": "नहीं बताना चाहते",
  "used_by": [
   "identity.sex=declined",
   "personal.menstrual=not_applicable"
  ],
  "asked": [
   {
    "qid": "identity.sex",
    "en": "Is the patient male or female?",
    "hi": "मरीज़ पुरुष हैं या महिला?"
   },
   {
    "qid": "personal.menstrual",
    "en": "How are your periods?",
    "hi": "आपकी माहवारी कैसी रहती है?"
   }
  ],
  "index": "012",
  "roman": "nahin bataana chaahte"
 },
 {
  "en": "Stomach pain",
  "hi": "पेट में दर्द",
  "used_by": [
   "cc.primary=abdominal_pain",
   "ros.gi=abdominal_pain"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   },
   {
    "qid": "ros.gi",
    "en": "Any trouble with your stomach or digestion?",
    "hi": "पेट या पाचन से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "013",
  "roman": "pet mein dard"
 },
 {
  "en": "Chest pain",
  "hi": "छाती में दर्द",
  "used_by": [
   "cc.primary=chest_pain",
   "ros.cardioresp=chest_pain"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   },
   {
    "qid": "ros.cardioresp",
    "en": "Any trouble with your chest, breathing or heart?",
    "hi": "छाती, साँस या दिल से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "014",
  "roman": "chaati mein dard"
 },
 {
  "en": "Headache",
  "hi": "सिर दर्द",
  "used_by": [
   "cc.primary=headache",
   "ros.neuro=headache"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   },
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "015",
  "roman": "sir dard"
 },
 {
  "en": "Joint or body pain",
  "hi": "जोड़ों या बदन में दर्द",
  "used_by": [
   "cc.primary=joint_pain"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "016",
  "roman": "jodon ya badan mein dard"
 },
 {
  "en": "Trouble breathing",
  "hi": "साँस लेने में तकलीफ़",
  "used_by": [
   "cc.primary=breathlessness"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "017",
  "roman": "saans lene mein takleef"
 },
 {
  "en": "Fever",
  "hi": "बुख़ार",
  "used_by": [
   "cc.primary=fever",
   "hpi.associated=fever",
   "ros.general=fever"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   },
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   },
   {
    "qid": "ros.general",
    "en": "Apart from all that, have you noticed any of these?",
    "hi": "इसके अलावा, क्या आपने इनमें से कुछ महसूस किया है?"
   }
  ],
  "index": "018",
  "roman": "bukhaar"
 },
 {
  "en": "Cough",
  "hi": "खाँसी",
  "used_by": [
   "cc.primary=cough",
   "ros.cardioresp=cough"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   },
   {
    "qid": "ros.cardioresp",
    "en": "Any trouble with your chest, breathing or heart?",
    "hi": "छाती, साँस या दिल से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "019",
  "roman": "khaansi"
 },
 {
  "en": "Skin problem",
  "hi": "त्वचा की समस्या",
  "used_by": [
   "cc.primary=skin_problem"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "020",
  "roman": "twacha ki samasya"
 },
 {
  "en": "Weakness or tiredness",
  "hi": "कमज़ोरी या थकान",
  "used_by": [
   "cc.primary=weakness_fatigue"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "021",
  "roman": "kamzori ya thakaan"
 },
 {
  "en": "Digestion problem",
  "hi": "पाचन की समस्या",
  "used_by": [
   "cc.primary=digestive_problem"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "022",
  "roman": "paachan ki samasya"
 },
 {
  "en": "Urine problem",
  "hi": "पेशाब की समस्या",
  "used_by": [
   "cc.primary=urinary_problem"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "023",
  "roman": "peshaab ki samasya"
 },
 {
  "en": "Periods problem",
  "hi": "माहवारी की समस्या",
  "used_by": [
   "cc.primary=menstrual_problem"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "024",
  "roman": "maahwaari ki samasya"
 },
 {
  "en": "Injury",
  "hi": "चोट",
  "used_by": [
   "cc.primary=injury"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   }
  ],
  "index": "025",
  "roman": "chot"
 },
 {
  "en": "Something else",
  "hi": "कुछ और",
  "used_by": [
   "cc.primary=other",
   "hpi.character=other_character"
  ],
  "asked": [
   {
    "qid": "cc.primary",
    "en": "What is troubling you today?",
    "hi": "आज आपको क्या तकलीफ़ है?"
   },
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "026",
  "roman": "kuch aur"
 },
 {
  "en": "Upper stomach",
  "hi": "पेट का ऊपरी हिस्सा",
  "used_by": [
   "hpi.site=upper_abdomen"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "027",
  "roman": "pet ka oopari hissa"
 },
 {
  "en": "Lower stomach",
  "hi": "पेट का निचला हिस्सा",
  "used_by": [
   "hpi.site=lower_abdomen"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "028",
  "roman": "pet ka nichla hissa"
 },
 {
  "en": "All over the stomach",
  "hi": "पूरे पेट में",
  "used_by": [
   "hpi.site=whole_abdomen"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "029",
  "roman": "poore pet mein"
 },
 {
  "en": "Middle of the chest",
  "hi": "छाती के बीच में",
  "used_by": [
   "hpi.site=central_chest"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "030",
  "roman": "chaati ke beech mein"
 },
 {
  "en": "Left side of the chest",
  "hi": "छाती के बाईं ओर",
  "used_by": [
   "hpi.site=left_chest"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "031",
  "roman": "chaati ke baayin or"
 },
 {
  "en": "Right side of the chest",
  "hi": "छाती के दाईं ओर",
  "used_by": [
   "hpi.site=right_chest"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "032",
  "roman": "chaati ke daayin or"
 },
 {
  "en": "Forehead",
  "hi": "माथे में",
  "used_by": [
   "hpi.site=forehead"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "033",
  "roman": "maathe mein"
 },
 {
  "en": "Back of the head",
  "hi": "सिर के पिछले हिस्से में",
  "used_by": [
   "hpi.site=back_of_head"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "034",
  "roman": "sir ke pichhle hisse mein"
 },
 {
  "en": "One side of the head",
  "hi": "सिर के एक तरफ़",
  "used_by": [
   "hpi.site=one_side_head"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "035",
  "roman": "sir ke ek taraf"
 },
 {
  "en": "The whole head",
  "hi": "पूरे सिर में",
  "used_by": [
   "hpi.site=whole_head"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "036",
  "roman": "poore sir mein"
 },
 {
  "en": "Knee",
  "hi": "घुटने में",
  "used_by": [
   "hpi.site=knee"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "037",
  "roman": "ghutne mein"
 },
 {
  "en": "Shoulder",
  "hi": "कंधे में",
  "used_by": [
   "hpi.site=shoulder"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "038",
  "roman": "kandhe mein"
 },
 {
  "en": "Lower back",
  "hi": "कमर में",
  "used_by": [
   "hpi.site=lower_back"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "039",
  "roman": "kamar mein"
 },
 {
  "en": "Neck",
  "hi": "गर्दन में",
  "used_by": [
   "hpi.site=neck"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "040",
  "roman": "gardan mein"
 },
 {
  "en": "Hip",
  "hi": "कूल्हे में",
  "used_by": [
   "hpi.site=hip"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "041",
  "roman": "koolhe mein"
 },
 {
  "en": "Many joints",
  "hi": "कई जोड़ों में",
  "used_by": [
   "hpi.site=multiple_joints"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   }
  ],
  "index": "042",
  "roman": "kai jodon mein"
 },
 {
  "en": "Somewhere else",
  "hi": "कहीं और",
  "used_by": [
   "hpi.site=other_site",
   "hpi.radiation=elsewhere"
  ],
  "asked": [
   {
    "qid": "hpi.site",
    "en": "Where exactly is it?",
    "hi": "दर्द ठीक कहाँ है?"
   },
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "043",
  "roman": "kahin aur"
 },
 {
  "en": "All of a sudden",
  "hi": "अचानक",
  "used_by": [
   "hpi.onset=sudden"
  ],
  "asked": [
   {
    "qid": "hpi.onset",
    "en": "Did it start suddenly, or slowly over time?",
    "hi": "क्या यह अचानक शुरू हुआ, या धीरे-धीरे?"
   }
  ],
  "index": "044",
  "roman": "achaanak"
 },
 {
  "en": "Slowly, over time",
  "hi": "धीरे-धीरे",
  "used_by": [
   "hpi.onset=gradual"
  ],
  "asked": [
   {
    "qid": "hpi.onset",
    "en": "Did it start suddenly, or slowly over time?",
    "hi": "क्या यह अचानक शुरू हुआ, या धीरे-धीरे?"
   }
  ],
  "index": "045",
  "roman": "dheere-dheere"
 },
 {
  "en": "I am not sure",
  "hi": "पता नहीं",
  "used_by": [
   "hpi.onset=unsure",
   "drugs.adherence=unsure"
  ],
  "asked": [
   {
    "qid": "hpi.onset",
    "en": "Did it start suddenly, or slowly over time?",
    "hi": "क्या यह अचानक शुरू हुआ, या धीरे-धीरे?"
   },
   {
    "qid": "drugs.adherence",
    "en": "Are you taking it regularly?",
    "hi": "क्या आप दवा नियमित रूप से ले रहे हैं?"
   }
  ],
  "index": "046",
  "roman": "pata nahin"
 },
 {
  "en": "hours",
  "hi": "घंटे",
  "used_by": [
   "hpi.duration=hours"
  ],
  "asked": [
   {
    "qid": "hpi.duration",
    "en": "How long have you had this?",
    "hi": "यह तकलीफ़ कब से है?"
   }
  ],
  "index": "047",
  "roman": "ghante"
 },
 {
  "en": "days",
  "hi": "दिन",
  "used_by": [
   "hpi.duration=days"
  ],
  "asked": [
   {
    "qid": "hpi.duration",
    "en": "How long have you had this?",
    "hi": "यह तकलीफ़ कब से है?"
   }
  ],
  "index": "048",
  "roman": "din"
 },
 {
  "en": "weeks",
  "hi": "हफ़्ते",
  "used_by": [
   "hpi.duration=weeks"
  ],
  "asked": [
   {
    "qid": "hpi.duration",
    "en": "How long have you had this?",
    "hi": "यह तकलीफ़ कब से है?"
   }
  ],
  "index": "049",
  "roman": "hafte"
 },
 {
  "en": "months",
  "hi": "महीने",
  "used_by": [
   "hpi.duration=months"
  ],
  "asked": [
   {
    "qid": "hpi.duration",
    "en": "How long have you had this?",
    "hi": "यह तकलीफ़ कब से है?"
   }
  ],
  "index": "050",
  "roman": "mahine"
 },
 {
  "en": "years",
  "hi": "साल",
  "used_by": [
   "hpi.duration=years"
  ],
  "asked": [
   {
    "qid": "hpi.duration",
    "en": "How long have you had this?",
    "hi": "यह तकलीफ़ कब से है?"
   }
  ],
  "index": "051",
  "roman": "saal"
 },
 {
  "en": "Burning",
  "hi": "जलन जैसा",
  "used_by": [
   "hpi.character=burning"
  ],
  "asked": [
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "052",
  "roman": "jalan jaisa"
 },
 {
  "en": "A dull ache",
  "hi": "हल्का सा दर्द",
  "used_by": [
   "hpi.character=dull_ache"
  ],
  "asked": [
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "053",
  "roman": "halka sa dard"
 },
 {
  "en": "Sharp, like a stab",
  "hi": "तेज़, चुभने जैसा",
  "used_by": [
   "hpi.character=sharp_stabbing"
  ],
  "asked": [
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "054",
  "roman": "tez, chubhne jaisa"
 },
 {
  "en": "Cramping, twisting",
  "hi": "मरोड़ जैसा",
  "used_by": [
   "hpi.character=cramping"
  ],
  "asked": [
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "055",
  "roman": "marod jaisa"
 },
 {
  "en": "Throbbing",
  "hi": "धड़कने जैसा",
  "used_by": [
   "hpi.character=throbbing"
  ],
  "asked": [
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "056",
  "roman": "dhadakne jaisa"
 },
 {
  "en": "Heavy, like pressure",
  "hi": "भारीपन या दबाव जैसा",
  "used_by": [
   "hpi.character=pressure_heavy"
  ],
  "asked": [
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "057",
  "roman": "bhaaripan ya dabaav jaisa"
 },
 {
  "en": "Tingling",
  "hi": "झनझनाहट",
  "used_by": [
   "hpi.character=tingling"
  ],
  "asked": [
   {
    "qid": "hpi.character",
    "en": "What does the pain feel like?",
    "hi": "दर्द कैसा महसूस होता है?"
   }
  ],
  "index": "058",
  "roman": "jhanjhanaahat"
 },
 {
  "en": "No, it stays in one place",
  "hi": "नहीं, एक ही जगह रहता है",
  "used_by": [
   "hpi.radiation=none"
  ],
  "asked": [
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "059",
  "roman": "nahin, ek hi jagah rehta hai"
 },
 {
  "en": "To the back",
  "hi": "पीठ की ओर",
  "used_by": [
   "hpi.radiation=to_back"
  ],
  "asked": [
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "060",
  "roman": "peeth ki or"
 },
 {
  "en": "To the left arm",
  "hi": "बाएँ हाथ की ओर",
  "used_by": [
   "hpi.radiation=to_left_arm"
  ],
  "asked": [
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "061",
  "roman": "baayen haath ki or"
 },
 {
  "en": "To the jaw or neck",
  "hi": "जबड़े या गर्दन की ओर",
  "used_by": [
   "hpi.radiation=to_jaw"
  ],
  "asked": [
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "062",
  "roman": "jabde ya gardan ki or"
 },
 {
  "en": "To the shoulder",
  "hi": "कंधे की ओर",
  "used_by": [
   "hpi.radiation=to_shoulder"
  ],
  "asked": [
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "063",
  "roman": "kandhe ki or"
 },
 {
  "en": "Down towards the groin",
  "hi": "नीचे कमर की ओर",
  "used_by": [
   "hpi.radiation=to_groin"
  ],
  "asked": [
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "064",
  "roman": "neeche kamar ki or"
 },
 {
  "en": "Down the leg",
  "hi": "पैर की ओर",
  "used_by": [
   "hpi.radiation=to_leg"
  ],
  "asked": [
   {
    "qid": "hpi.radiation",
    "en": "Does the pain travel anywhere else?",
    "hi": "क्या दर्द कहीं और भी जाता है?"
   }
  ],
  "index": "065",
  "roman": "pair ki or"
 },
 {
  "en": "Feeling sick",
  "hi": "जी मिचलाना",
  "used_by": [
   "hpi.associated=nausea"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "066",
  "roman": "ji michlaana"
 },
 {
  "en": "Vomiting",
  "hi": "उल्टी",
  "used_by": [
   "hpi.associated=vomiting",
   "ros.gi=vomiting"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   },
   {
    "qid": "ros.gi",
    "en": "Any trouble with your stomach or digestion?",
    "hi": "पेट या पाचन से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "067",
  "roman": "ulti"
 },
 {
  "en": "Heavy sweating",
  "hi": "बहुत पसीना",
  "used_by": [
   "hpi.associated=sweating"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "068",
  "roman": "bahut paseena"
 },
 {
  "en": "Giddiness",
  "hi": "चक्कर",
  "used_by": [
   "hpi.associated=dizziness",
   "ros.neuro=giddiness"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   },
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "069",
  "roman": "chakkar"
 },
 {
  "en": "Trouble breathing",
  "hi": "साँस फूलना",
  "used_by": [
   "hpi.associated=breathlessness"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "070",
  "roman": "saans phoolna"
 },
 {
  "en": "Heart racing",
  "hi": "दिल तेज़ धड़कना",
  "used_by": [
   "hpi.associated=palpitations",
   "ros.cardioresp=palpitations"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   },
   {
    "qid": "ros.cardioresp",
    "en": "Any trouble with your chest, breathing or heart?",
    "hi": "छाती, साँस या दिल से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "071",
  "roman": "dil tez dhadakna"
 },
 {
  "en": "Loose motions",
  "hi": "दस्त",
  "used_by": [
   "hpi.associated=loose_motion"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "072",
  "roman": "dast"
 },
 {
  "en": "Constipation",
  "hi": "क़ब्ज़",
  "used_by": [
   "hpi.associated=constipation"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "073",
  "roman": "kabz"
 },
 {
  "en": "Losing weight",
  "hi": "वज़न घटना",
  "used_by": [
   "hpi.associated=weight_loss"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "074",
  "roman": "wazan ghatna"
 },
 {
  "en": "No appetite",
  "hi": "भूख न लगना",
  "used_by": [
   "hpi.associated=appetite_loss"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "075",
  "roman": "bhookh na lagna"
 },
 {
  "en": "Nothing else",
  "hi": "और कुछ नहीं",
  "used_by": [
   "hpi.associated=none"
  ],
  "asked": [
   {
    "qid": "hpi.associated",
    "en": "Is anything else happening along with it?",
    "hi": "इसके साथ और कुछ भी हो रहा है?"
   }
  ],
  "index": "076",
  "roman": "aur kuch nahin"
 },
 {
  "en": "All the time",
  "hi": "हमेशा",
  "used_by": [
   "hpi.timing=constant"
  ],
  "asked": [
   {
    "qid": "hpi.timing",
    "en": "Is it there all the time, or does it come and go?",
    "hi": "क्या यह हमेशा रहता है, या आता-जाता है?"
   }
  ],
  "index": "077",
  "roman": "hamesha"
 },
 {
  "en": "Comes and goes",
  "hi": "आता-जाता है",
  "used_by": [
   "hpi.timing=comes_and_goes"
  ],
  "asked": [
   {
    "qid": "hpi.timing",
    "en": "Is it there all the time, or does it come and go?",
    "hi": "क्या यह हमेशा रहता है, या आता-जाता है?"
   }
  ],
  "index": "078",
  "roman": "aata-jaata hai"
 },
 {
  "en": "Worse in the morning",
  "hi": "सुबह ज़्यादा",
  "used_by": [
   "hpi.timing=worse_morning"
  ],
  "asked": [
   {
    "qid": "hpi.timing",
    "en": "Is it there all the time, or does it come and go?",
    "hi": "क्या यह हमेशा रहता है, या आता-जाता है?"
   }
  ],
  "index": "079",
  "roman": "subah zyada"
 },
 {
  "en": "Worse at night",
  "hi": "रात में ज़्यादा",
  "used_by": [
   "hpi.timing=worse_night"
  ],
  "asked": [
   {
    "qid": "hpi.timing",
    "en": "Is it there all the time, or does it come and go?",
    "hi": "क्या यह हमेशा रहता है, या आता-जाता है?"
   }
  ],
  "index": "080",
  "roman": "raat mein zyada"
 },
 {
  "en": "Worse after eating",
  "hi": "खाने के बाद ज़्यादा",
  "used_by": [
   "hpi.timing=worse_after_food"
  ],
  "asked": [
   {
    "qid": "hpi.timing",
    "en": "Is it there all the time, or does it come and go?",
    "hi": "क्या यह हमेशा रहता है, या आता-जाता है?"
   }
  ],
  "index": "081",
  "roman": "khaane ke baad zyada"
 },
 {
  "en": "Worse on an empty stomach",
  "hi": "खाली पेट ज़्यादा",
  "used_by": [
   "hpi.timing=worse_empty_stomach"
  ],
  "asked": [
   {
    "qid": "hpi.timing",
    "en": "Is it there all the time, or does it come and go?",
    "hi": "क्या यह हमेशा रहता है, या आता-जाता है?"
   }
  ],
  "index": "082",
  "roman": "khaali pet zyada"
 },
 {
  "en": "No particular pattern",
  "hi": "कोई ख़ास बात नहीं",
  "used_by": [
   "hpi.timing=unrelated"
  ],
  "asked": [
   {
    "qid": "hpi.timing",
    "en": "Is it there all the time, or does it come and go?",
    "hi": "क्या यह हमेशा रहता है, या आता-जाता है?"
   }
  ],
  "index": "083",
  "roman": "koi khaas baat nahin"
 },
 {
  "en": "Eating",
  "hi": "खाना खाने से",
  "used_by": [
   "hpi.aggravating=eating"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "084",
  "roman": "khaana khaane se"
 },
 {
  "en": "An empty stomach",
  "hi": "खाली पेट रहने से",
  "used_by": [
   "hpi.aggravating=empty_stomach"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "085",
  "roman": "khaali pet rehne se"
 },
 {
  "en": "Moving about",
  "hi": "चलने-फिरने से",
  "used_by": [
   "hpi.aggravating=movement"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "086",
  "roman": "chalne-phirne se"
 },
 {
  "en": "Resting",
  "hi": "आराम करने से",
  "used_by": [
   "hpi.aggravating=rest",
   "hpi.relieving=rest"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   },
   {
    "qid": "hpi.relieving",
    "en": "What makes it better?",
    "hi": "किस चीज़ से आराम मिलता है?"
   }
  ],
  "index": "087",
  "roman": "aaraam karne se"
 },
 {
  "en": "Lying down",
  "hi": "लेटने से",
  "used_by": [
   "hpi.aggravating=lying_down"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "088",
  "roman": "letne se"
 },
 {
  "en": "Worry or tension",
  "hi": "चिंता या तनाव से",
  "used_by": [
   "hpi.aggravating=stress"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "089",
  "roman": "chinta ya tanaav se"
 },
 {
  "en": "Cold weather",
  "hi": "ठंड से",
  "used_by": [
   "hpi.aggravating=cold"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "090",
  "roman": "thand se"
 },
 {
  "en": "Heat",
  "hi": "गर्मी से",
  "used_by": [
   "hpi.aggravating=heat"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "091",
  "roman": "garmi se"
 },
 {
  "en": "Certain foods",
  "hi": "कुछ ख़ास खाने से",
  "used_by": [
   "hpi.aggravating=certain_foods"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "092",
  "roman": "kuch khaas khaane se"
 },
 {
  "en": "Nothing in particular",
  "hi": "कोई ख़ास चीज़ नहीं",
  "used_by": [
   "hpi.aggravating=nothing_particular"
  ],
  "asked": [
   {
    "qid": "hpi.aggravating",
    "en": "What makes it worse?",
    "hi": "किस चीज़ से यह बढ़ जाता है?"
   }
  ],
  "index": "093",
  "roman": "koi khaas cheez nahin"
 },
 {
  "en": "Taking medicine",
  "hi": "दवा लेने से",
  "used_by": [
   "hpi.relieving=medicine"
  ],
  "asked": [
   {
    "qid": "hpi.relieving",
    "en": "What makes it better?",
    "hi": "किस चीज़ से आराम मिलता है?"
   }
  ],
  "index": "094",
  "roman": "dawa lene se"
 },
 {
  "en": "Eating something",
  "hi": "कुछ खाने से",
  "used_by": [
   "hpi.relieving=food"
  ],
  "asked": [
   {
    "qid": "hpi.relieving",
    "en": "What makes it better?",
    "hi": "किस चीज़ से आराम मिलता है?"
   }
  ],
  "index": "095",
  "roman": "kuch khaane se"
 },
 {
  "en": "After vomiting",
  "hi": "उल्टी के बाद",
  "used_by": [
   "hpi.relieving=vomiting"
  ],
  "asked": [
   {
    "qid": "hpi.relieving",
    "en": "What makes it better?",
    "hi": "किस चीज़ से आराम मिलता है?"
   }
  ],
  "index": "096",
  "roman": "ulti ke baad"
 },
 {
  "en": "After passing stool",
  "hi": "शौच के बाद",
  "used_by": [
   "hpi.relieving=passing_stool"
  ],
  "asked": [
   {
    "qid": "hpi.relieving",
    "en": "What makes it better?",
    "hi": "किस चीज़ से आराम मिलता है?"
   }
  ],
  "index": "097",
  "roman": "shauch ke baad"
 },
 {
  "en": "Warmth or a hot compress",
  "hi": "सिंकाई या गर्मी से",
  "used_by": [
   "hpi.relieving=warmth"
  ],
  "asked": [
   {
    "qid": "hpi.relieving",
    "en": "What makes it better?",
    "hi": "किस चीज़ से आराम मिलता है?"
   }
  ],
  "index": "098",
  "roman": "sinkaai ya garmi se"
 },
 {
  "en": "Nothing helps",
  "hi": "किसी चीज़ से नहीं",
  "used_by": [
   "hpi.relieving=nothing_helps"
  ],
  "asked": [
   {
    "qid": "hpi.relieving",
    "en": "What makes it better?",
    "hi": "किस चीज़ से आराम मिलता है?"
   }
  ],
  "index": "099",
  "roman": "kisi cheez se nahin"
 },
 {
  "en": "Getting worse",
  "hi": "बढ़ रहा है",
  "used_by": [
   "hpi.progression=getting_worse"
  ],
  "asked": [
   {
    "qid": "hpi.progression",
    "en": "Since it started, is it getting worse, getting better, or staying the same?",
    "hi": "शुरू होने के बाद से यह बढ़ रहा है, कम हो रहा है, या वैसा ही है?"
   }
  ],
  "index": "100",
  "roman": "badh raha hai"
 },
 {
  "en": "Getting better",
  "hi": "कम हो रहा है",
  "used_by": [
   "hpi.progression=getting_better"
  ],
  "asked": [
   {
    "qid": "hpi.progression",
    "en": "Since it started, is it getting worse, getting better, or staying the same?",
    "hi": "शुरू होने के बाद से यह बढ़ रहा है, कम हो रहा है, या वैसा ही है?"
   }
  ],
  "index": "101",
  "roman": "kam ho raha hai"
 },
 {
  "en": "About the same",
  "hi": "वैसा ही है",
  "used_by": [
   "hpi.progression=same"
  ],
  "asked": [
   {
    "qid": "hpi.progression",
    "en": "Since it started, is it getting worse, getting better, or staying the same?",
    "hi": "शुरू होने के बाद से यह बढ़ रहा है, कम हो रहा है, या वैसा ही है?"
   }
  ],
  "index": "102",
  "roman": "waisa hi hai"
 },
 {
  "en": "Up and down",
  "hi": "कभी ज़्यादा कभी कम",
  "used_by": [
   "hpi.progression=fluctuating"
  ],
  "asked": [
   {
    "qid": "hpi.progression",
    "en": "Since it started, is it getting worse, getting better, or staying the same?",
    "hi": "शुरू होने के बाद से यह बढ़ रहा है, कम हो रहा है, या वैसा ही है?"
   }
  ],
  "index": "103",
  "roman": "kabhi zyada kabhi kam"
 },
 {
  "en": "Yes, the first time",
  "hi": "हाँ, पहली बार",
  "used_by": [
   "hpi.first_episode=True"
  ],
  "asked": [
   {
    "qid": "hpi.first_episode",
    "en": "Is this the first time this has happened?",
    "hi": "क्या यह पहली बार हुआ है?"
   }
  ],
  "index": "104",
  "roman": "haan, pehli baar"
 },
 {
  "en": "No, it has happened before",
  "hi": "नहीं, पहले भी हुआ है",
  "used_by": [
   "hpi.first_episode=False"
  ],
  "asked": [
   {
    "qid": "hpi.first_episode",
    "en": "Is this the first time this has happened?",
    "hi": "क्या यह पहली बार हुआ है?"
   }
  ],
  "index": "105",
  "roman": "nahin, pehle bhi hua hai"
 },
 {
  "en": "Diabetes (sugar)",
  "hi": "मधुमेह (शुगर)",
  "used_by": [
   "past.conditions=diabetes",
   "family.conditions=diabetes"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "106",
  "roman": "madhumeh (sugar)"
 },
 {
  "en": "High blood pressure",
  "hi": "उच्च रक्तचाप (बी.पी.)",
  "used_by": [
   "past.conditions=hypertension"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   }
  ],
  "index": "107",
  "roman": "uchch raktchaap (B.P.)"
 },
 {
  "en": "Heart disease",
  "hi": "दिल की बीमारी",
  "used_by": [
   "past.conditions=heart_disease",
   "family.conditions=heart_disease"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "108",
  "roman": "dil ki beemaari"
 },
 {
  "en": "Asthma",
  "hi": "दमा",
  "used_by": [
   "past.conditions=asthma",
   "family.conditions=asthma"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "109",
  "roman": "dama"
 },
 {
  "en": "Tuberculosis (TB)",
  "hi": "टी.बी.",
  "used_by": [
   "past.conditions=tuberculosis",
   "family.conditions=tuberculosis"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "110",
  "roman": "T.B."
 },
 {
  "en": "Thyroid problem",
  "hi": "थायरॉइड",
  "used_by": [
   "past.conditions=thyroid"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   }
  ],
  "index": "111",
  "roman": "thyroid"
 },
 {
  "en": "Kidney disease",
  "hi": "गुर्दे की बीमारी",
  "used_by": [
   "past.conditions=kidney_disease"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   }
  ],
  "index": "112",
  "roman": "gurde ki beemaari"
 },
 {
  "en": "Liver disease",
  "hi": "जिगर की बीमारी",
  "used_by": [
   "past.conditions=liver_disease"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   }
  ],
  "index": "113",
  "roman": "jigar ki beemaari"
 },
 {
  "en": "Paralysis or stroke",
  "hi": "लकवा",
  "used_by": [
   "past.conditions=stroke",
   "family.conditions=stroke"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "114",
  "roman": "lakwa"
 },
 {
  "en": "Cancer",
  "hi": "कैंसर",
  "used_by": [
   "past.conditions=cancer",
   "family.conditions=cancer"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "115",
  "roman": "cancer"
 },
 {
  "en": "Fits",
  "hi": "मिर्गी",
  "used_by": [
   "past.conditions=epilepsy"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   }
  ],
  "index": "116",
  "roman": "mirgi"
 },
 {
  "en": "Arthritis",
  "hi": "गठिया",
  "used_by": [
   "past.conditions=arthritis"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   }
  ],
  "index": "117",
  "roman": "gathiya"
 },
 {
  "en": "None of these",
  "hi": "इनमें से कोई नहीं",
  "used_by": [
   "past.conditions=none",
   "family.conditions=none",
   "ros.danger_signs=none",
   "ros.general=none",
   "ros.cardioresp=none",
   "ros.gi=none",
   "ros.neuro=none",
   "ros.uro=none"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   },
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.general",
    "en": "Apart from all that, have you noticed any of these?",
    "hi": "इसके अलावा, क्या आपने इनमें से कुछ महसूस किया है?"
   },
   {
    "qid": "ros.cardioresp",
    "en": "Any trouble with your chest, breathing or heart?",
    "hi": "छाती, साँस या दिल से जुड़ी कोई तकलीफ़?"
   },
   {
    "qid": "ros.gi",
    "en": "Any trouble with your stomach or digestion?",
    "hi": "पेट या पाचन से जुड़ी कोई तकलीफ़?"
   },
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   },
   {
    "qid": "ros.uro",
    "en": "Any trouble passing urine?",
    "hi": "पेशाब से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "118",
  "roman": "inmein se koi nahin"
 },
 {
  "en": "I do not know",
  "hi": "पता नहीं",
  "used_by": [
   "past.conditions=unsure",
   "drugs.allergy_known=unsure",
   "family.conditions=unsure"
  ],
  "asked": [
   {
    "qid": "past.conditions",
    "en": "Has a doctor ever told you that you have any of these?",
    "hi": "क्या डॉक्टर ने कभी बताया है कि आपको इनमें से कुछ है?"
   },
   {
    "qid": "drugs.allergy_known",
    "en": "Has any medicine or food ever given you a reaction?",
    "hi": "क्या किसी दवा या खाने से आपको कभी कोई प्रतिक्रिया हुई है?"
   },
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "119",
  "roman": "pata nahin"
 },
 {
  "en": "Yes",
  "hi": "हाँ",
  "used_by": [
   "past.surgeries=True",
   "drugs.taking_now=True"
  ],
  "asked": [
   {
    "qid": "past.surgeries",
    "en": "Have you ever had an operation?",
    "hi": "क्या आपका कभी ऑपरेशन हुआ है?"
   },
   {
    "qid": "drugs.taking_now",
    "en": "Are you taking any medicine at the moment?",
    "hi": "क्या आप अभी कोई दवा ले रहे हैं?"
   }
  ],
  "index": "120",
  "roman": "haan"
 },
 {
  "en": "No",
  "hi": "नहीं",
  "used_by": [
   "past.surgeries=False",
   "drugs.taking_now=False"
  ],
  "asked": [
   {
    "qid": "past.surgeries",
    "en": "Have you ever had an operation?",
    "hi": "क्या आपका कभी ऑपरेशन हुआ है?"
   },
   {
    "qid": "drugs.taking_now",
    "en": "Are you taking any medicine at the moment?",
    "hi": "क्या आप अभी कोई दवा ले रहे हैं?"
   }
  ],
  "index": "121",
  "roman": "nahin"
 },
 {
  "en": "Never",
  "hi": "कभी नहीं",
  "used_by": [
   "past.hospitalisation=never",
   "personal.tobacco=never",
   "personal.alcohol=never"
  ],
  "asked": [
   {
    "qid": "past.hospitalisation",
    "en": "When were you last admitted to a hospital?",
    "hi": "आप आख़िरी बार अस्पताल में कब भर्ती हुए थे?"
   },
   {
    "qid": "personal.tobacco",
    "en": "Do you use tobacco in any form?",
    "hi": "क्या आप किसी भी रूप में तंबाकू लेते हैं?"
   },
   {
    "qid": "personal.alcohol",
    "en": "Do you drink alcohol?",
    "hi": "क्या आप शराब पीते हैं?"
   }
  ],
  "index": "122",
  "roman": "kabhi nahin"
 },
 {
  "en": "Within the last year",
  "hi": "पिछले एक साल में",
  "used_by": [
   "past.hospitalisation=within_year"
  ],
  "asked": [
   {
    "qid": "past.hospitalisation",
    "en": "When were you last admitted to a hospital?",
    "hi": "आप आख़िरी बार अस्पताल में कब भर्ती हुए थे?"
   }
  ],
  "index": "123",
  "roman": "pichhle ek saal mein"
 },
 {
  "en": "One to five years ago",
  "hi": "एक से पाँच साल पहले",
  "used_by": [
   "past.hospitalisation=one_to_five_years"
  ],
  "asked": [
   {
    "qid": "past.hospitalisation",
    "en": "When were you last admitted to a hospital?",
    "hi": "आप आख़िरी बार अस्पताल में कब भर्ती हुए थे?"
   }
  ],
  "index": "124",
  "roman": "ek se paanch saal pehle"
 },
 {
  "en": "More than five years ago",
  "hi": "पाँच साल से ज़्यादा पहले",
  "used_by": [
   "past.hospitalisation=over_five_years"
  ],
  "asked": [
   {
    "qid": "past.hospitalisation",
    "en": "When were you last admitted to a hospital?",
    "hi": "आप आख़िरी बार अस्पताल में कब भर्ती हुए थे?"
   }
  ],
  "index": "125",
  "roman": "paanch saal se zyada pehle"
 },
 {
  "en": "I do not remember",
  "hi": "याद नहीं",
  "used_by": [
   "past.hospitalisation=unsure"
  ],
  "asked": [
   {
    "qid": "past.hospitalisation",
    "en": "When were you last admitted to a hospital?",
    "hi": "आप आख़िरी बार अस्पताल में कब भर्ती हुए थे?"
   }
  ],
  "index": "126",
  "roman": "yaad nahin"
 },
 {
  "en": "English medicine",
  "hi": "अंग्रेज़ी दवा",
  "used_by": [
   "drugs.systems=allopathic"
  ],
  "asked": [
   {
    "qid": "drugs.systems",
    "en": "What kind of medicine is it?",
    "hi": "किस तरह की दवा है?"
   }
  ],
  "index": "127",
  "roman": "angrezi dawa"
 },
 {
  "en": "Ayurvedic",
  "hi": "आयुर्वेदिक",
  "used_by": [
   "drugs.systems=ayurvedic"
  ],
  "asked": [
   {
    "qid": "drugs.systems",
    "en": "What kind of medicine is it?",
    "hi": "किस तरह की दवा है?"
   }
  ],
  "index": "128",
  "roman": "ayurvedic"
 },
 {
  "en": "Homeopathic",
  "hi": "होम्योपैथिक",
  "used_by": [
   "drugs.systems=homeopathic"
  ],
  "asked": [
   {
    "qid": "drugs.systems",
    "en": "What kind of medicine is it?",
    "hi": "किस तरह की दवा है?"
   }
  ],
  "index": "129",
  "roman": "homeopathic"
 },
 {
  "en": "Siddha",
  "hi": "सिद्ध",
  "used_by": [
   "drugs.systems=siddha"
  ],
  "asked": [
   {
    "qid": "drugs.systems",
    "en": "What kind of medicine is it?",
    "hi": "किस तरह की दवा है?"
   }
  ],
  "index": "130",
  "roman": "siddha"
 },
 {
  "en": "Unani",
  "hi": "यूनानी",
  "used_by": [
   "drugs.systems=unani"
  ],
  "asked": [
   {
    "qid": "drugs.systems",
    "en": "What kind of medicine is it?",
    "hi": "किस तरह की दवा है?"
   }
  ],
  "index": "131",
  "roman": "unani"
 },
 {
  "en": "Something I take on my own",
  "hi": "अपने आप ली जाने वाली",
  "used_by": [
   "drugs.systems=self_medication"
  ],
  "asked": [
   {
    "qid": "drugs.systems",
    "en": "What kind of medicine is it?",
    "hi": "किस तरह की दवा है?"
   }
  ],
  "index": "132",
  "roman": "apne aap li jaane waali"
 },
 {
  "en": "None",
  "hi": "कोई नहीं",
  "used_by": [
   "drugs.systems=none"
  ],
  "asked": [
   {
    "qid": "drugs.systems",
    "en": "What kind of medicine is it?",
    "hi": "किस तरह की दवा है?"
   }
  ],
  "index": "133",
  "roman": "koi nahin"
 },
 {
  "en": "Yes, every day",
  "hi": "हाँ, रोज़",
  "used_by": [
   "drugs.adherence=regular"
  ],
  "asked": [
   {
    "qid": "drugs.adherence",
    "en": "Are you taking it regularly?",
    "hi": "क्या आप दवा नियमित रूप से ले रहे हैं?"
   }
  ],
  "index": "134",
  "roman": "haan, roz"
 },
 {
  "en": "I miss it sometimes",
  "hi": "कभी-कभी छूट जाती है",
  "used_by": [
   "drugs.adherence=sometimes_missed"
  ],
  "asked": [
   {
    "qid": "drugs.adherence",
    "en": "Are you taking it regularly?",
    "hi": "क्या आप दवा नियमित रूप से ले रहे हैं?"
   }
  ],
  "index": "135",
  "roman": "kabhi-kabhi chhoot jaati hai"
 },
 {
  "en": "I stopped taking it",
  "hi": "मैंने लेना बंद कर दिया",
  "used_by": [
   "drugs.adherence=stopped"
  ],
  "asked": [
   {
    "qid": "drugs.adherence",
    "en": "Are you taking it regularly?",
    "hi": "क्या आप दवा नियमित रूप से ले रहे हैं?"
   }
  ],
  "index": "136",
  "roman": "maine lena band kar diya"
 },
 {
  "en": "No, never",
  "hi": "नहीं, कभी नहीं",
  "used_by": [
   "drugs.allergy_known=none"
  ],
  "asked": [
   {
    "qid": "drugs.allergy_known",
    "en": "Has any medicine or food ever given you a reaction?",
    "hi": "क्या किसी दवा या खाने से आपको कभी कोई प्रतिक्रिया हुई है?"
   }
  ],
  "index": "137",
  "roman": "nahin, kabhi nahin"
 },
 {
  "en": "Yes, from a medicine",
  "hi": "हाँ, दवा से",
  "used_by": [
   "drugs.allergy_known=drug_allergy"
  ],
  "asked": [
   {
    "qid": "drugs.allergy_known",
    "en": "Has any medicine or food ever given you a reaction?",
    "hi": "क्या किसी दवा या खाने से आपको कभी कोई प्रतिक्रिया हुई है?"
   }
  ],
  "index": "138",
  "roman": "haan, dawa se"
 },
 {
  "en": "Yes, from a food",
  "hi": "हाँ, खाने से",
  "used_by": [
   "drugs.allergy_known=food_allergy"
  ],
  "asked": [
   {
    "qid": "drugs.allergy_known",
    "en": "Has any medicine or food ever given you a reaction?",
    "hi": "क्या किसी दवा या खाने से आपको कभी कोई प्रतिक्रिया हुई है?"
   }
  ],
  "index": "139",
  "roman": "haan, khaane se"
 },
 {
  "en": "Yes, from both",
  "hi": "हाँ, दोनों से",
  "used_by": [
   "drugs.allergy_known=both"
  ],
  "asked": [
   {
    "qid": "drugs.allergy_known",
    "en": "Has any medicine or food ever given you a reaction?",
    "hi": "क्या किसी दवा या खाने से आपको कभी कोई प्रतिक्रिया हुई है?"
   }
  ],
  "index": "140",
  "roman": "haan, donon se"
 },
 {
  "en": "High blood pressure",
  "hi": "उच्च रक्तचाप",
  "used_by": [
   "family.conditions=hypertension"
  ],
  "asked": [
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "141",
  "roman": "uchch raktchaap"
 },
 {
  "en": "Mental illness",
  "hi": "मानसिक बीमारी",
  "used_by": [
   "family.conditions=mental_illness"
  ],
  "asked": [
   {
    "qid": "family.conditions",
    "en": "Does anyone in your close family have any of these?",
    "hi": "क्या आपके परिवार में किसी को इनमें से कुछ है?"
   }
  ],
  "index": "142",
  "roman": "maansik beemaari"
 },
 {
  "en": "Vegetarian",
  "hi": "शाकाहारी",
  "used_by": [
   "personal.diet=vegetarian"
  ],
  "asked": [
   {
    "qid": "personal.diet",
    "en": "What do you normally eat?",
    "hi": "आप आम तौर पर क्या खाते हैं?"
   }
  ],
  "index": "143",
  "roman": "shaakaahaari"
 },
 {
  "en": "Non-vegetarian",
  "hi": "मांसाहारी",
  "used_by": [
   "personal.diet=non_vegetarian"
  ],
  "asked": [
   {
    "qid": "personal.diet",
    "en": "What do you normally eat?",
    "hi": "आप आम तौर पर क्या खाते हैं?"
   }
  ],
  "index": "144",
  "roman": "maansaahaari"
 },
 {
  "en": "Vegetarian with eggs",
  "hi": "अंडा खाते हैं",
  "used_by": [
   "personal.diet=eggetarian"
  ],
  "asked": [
   {
    "qid": "personal.diet",
    "en": "What do you normally eat?",
    "hi": "आप आम तौर पर क्या खाते हैं?"
   }
  ],
  "index": "145",
  "roman": "anda khaate hain"
 },
 {
  "en": "No animal products at all",
  "hi": "पूरी तरह शाकाहारी (दूध भी नहीं)",
  "used_by": [
   "personal.diet=vegan"
  ],
  "asked": [
   {
    "qid": "personal.diet",
    "en": "What do you normally eat?",
    "hi": "आप आम तौर पर क्या खाते हैं?"
   }
  ],
  "index": "146",
  "roman": "poori tarah shaakaahaari (doodh bhi nahin)"
 },
 {
  "en": "Chewing tobacco, gutkha",
  "hi": "खैनी, गुटखा",
  "used_by": [
   "personal.tobacco=chewing"
  ],
  "asked": [
   {
    "qid": "personal.tobacco",
    "en": "Do you use tobacco in any form?",
    "hi": "क्या आप किसी भी रूप में तंबाकू लेते हैं?"
   }
  ],
  "index": "147",
  "roman": "khaini, gutkha"
 },
 {
  "en": "Smoking",
  "hi": "धूम्रपान",
  "used_by": [
   "personal.tobacco=smoking"
  ],
  "asked": [
   {
    "qid": "personal.tobacco",
    "en": "Do you use tobacco in any form?",
    "hi": "क्या आप किसी भी रूप में तंबाकू लेते हैं?"
   }
  ],
  "index": "148",
  "roman": "dhoomrapaan"
 },
 {
  "en": "Both",
  "hi": "दोनों",
  "used_by": [
   "personal.tobacco=both"
  ],
  "asked": [
   {
    "qid": "personal.tobacco",
    "en": "Do you use tobacco in any form?",
    "hi": "क्या आप किसी भी रूप में तंबाकू लेते हैं?"
   }
  ],
  "index": "149",
  "roman": "donon"
 },
 {
  "en": "I used to, but stopped",
  "hi": "पहले लेते थे, अब छोड़ दिया",
  "used_by": [
   "personal.tobacco=quit"
  ],
  "asked": [
   {
    "qid": "personal.tobacco",
    "en": "Do you use tobacco in any form?",
    "hi": "क्या आप किसी भी रूप में तंबाकू लेते हैं?"
   }
  ],
  "index": "150",
  "roman": "pehle lete the, ab chhod diya"
 },
 {
  "en": "Once in a while",
  "hi": "कभी-कभार",
  "used_by": [
   "personal.alcohol=occasional"
  ],
  "asked": [
   {
    "qid": "personal.alcohol",
    "en": "Do you drink alcohol?",
    "hi": "क्या आप शराब पीते हैं?"
   }
  ],
  "index": "151",
  "roman": "kabhi-kabhaar"
 },
 {
  "en": "Regularly",
  "hi": "नियमित रूप से",
  "used_by": [
   "personal.alcohol=regular"
  ],
  "asked": [
   {
    "qid": "personal.alcohol",
    "en": "Do you drink alcohol?",
    "hi": "क्या आप शराब पीते हैं?"
   }
  ],
  "index": "152",
  "roman": "niyamit roop se"
 },
 {
  "en": "I used to, but stopped",
  "hi": "पहले पीते थे, अब छोड़ दिया",
  "used_by": [
   "personal.alcohol=quit"
  ],
  "asked": [
   {
    "qid": "personal.alcohol",
    "en": "Do you drink alcohol?",
    "hi": "क्या आप शराब पीते हैं?"
   }
  ],
  "index": "153",
  "roman": "pehle peete the, ab chhod diya"
 },
 {
  "en": "Good",
  "hi": "अच्छी",
  "used_by": [
   "personal.sleep=good"
  ],
  "asked": [
   {
    "qid": "personal.sleep",
    "en": "How is your sleep?",
    "hi": "आपकी नींद कैसी है?"
   }
  ],
  "index": "154",
  "roman": "achchhi"
 },
 {
  "en": "Hard to fall asleep",
  "hi": "नींद देर से आती है",
  "used_by": [
   "personal.sleep=difficulty_falling"
  ],
  "asked": [
   {
    "qid": "personal.sleep",
    "en": "How is your sleep?",
    "hi": "आपकी नींद कैसी है?"
   }
  ],
  "index": "155",
  "roman": "neend der se aati hai"
 },
 {
  "en": "I wake up often",
  "hi": "बार-बार नींद खुलती है",
  "used_by": [
   "personal.sleep=waking_often"
  ],
  "asked": [
   {
    "qid": "personal.sleep",
    "en": "How is your sleep?",
    "hi": "आपकी नींद कैसी है?"
   }
  ],
  "index": "156",
  "roman": "baar-baar neend khulti hai"
 },
 {
  "en": "Too little sleep",
  "hi": "बहुत कम नींद",
  "used_by": [
   "personal.sleep=too_little"
  ],
  "asked": [
   {
    "qid": "personal.sleep",
    "en": "How is your sleep?",
    "hi": "आपकी नींद कैसी है?"
   }
  ],
  "index": "157",
  "roman": "bahut kam neend"
 },
 {
  "en": "Too much sleep",
  "hi": "बहुत ज़्यादा नींद",
  "used_by": [
   "personal.sleep=too_much"
  ],
  "asked": [
   {
    "qid": "personal.sleep",
    "en": "How is your sleep?",
    "hi": "आपकी नींद कैसी है?"
   }
  ],
  "index": "158",
  "roman": "bahut zyada neend"
 },
 {
  "en": "Regular",
  "hi": "नियमित",
  "used_by": [
   "personal.bowel=regular",
   "personal.menstrual=regular"
  ],
  "asked": [
   {
    "qid": "personal.bowel",
    "en": "How are your bowel movements?",
    "hi": "आपका शौच कैसा रहता है?"
   },
   {
    "qid": "personal.menstrual",
    "en": "How are your periods?",
    "hi": "आपकी माहवारी कैसी रहती है?"
   }
  ],
  "index": "159",
  "roman": "niyamit"
 },
 {
  "en": "Constipated",
  "hi": "क़ब्ज़ रहता है",
  "used_by": [
   "personal.bowel=constipated"
  ],
  "asked": [
   {
    "qid": "personal.bowel",
    "en": "How are your bowel movements?",
    "hi": "आपका शौच कैसा रहता है?"
   }
  ],
  "index": "160",
  "roman": "kabz rehta hai"
 },
 {
  "en": "Loose",
  "hi": "पतला",
  "used_by": [
   "personal.bowel=loose"
  ],
  "asked": [
   {
    "qid": "personal.bowel",
    "en": "How are your bowel movements?",
    "hi": "आपका शौच कैसा रहता है?"
   }
  ],
  "index": "161",
  "roman": "patla"
 },
 {
  "en": "Sometimes one, sometimes the other",
  "hi": "कभी क़ब्ज़, कभी पतला",
  "used_by": [
   "personal.bowel=alternating"
  ],
  "asked": [
   {
    "qid": "personal.bowel",
    "en": "How are your bowel movements?",
    "hi": "आपका शौच कैसा रहता है?"
   }
  ],
  "index": "162",
  "roman": "kabhi kabz, kabhi patla"
 },
 {
  "en": "Mostly sitting",
  "hi": "ज़्यादातर बैठकर",
  "used_by": [
   "personal.occupation_strain=sedentary"
  ],
  "asked": [
   {
    "qid": "personal.occupation_strain",
    "en": "What is your work like?",
    "hi": "आपका काम कैसा है?"
   }
  ],
  "index": "163",
  "roman": "zyadatar baithkar"
 },
 {
  "en": "Standing for long hours",
  "hi": "लंबे समय खड़े रहकर",
  "used_by": [
   "personal.occupation_strain=standing_long"
  ],
  "asked": [
   {
    "qid": "personal.occupation_strain",
    "en": "What is your work like?",
    "hi": "आपका काम कैसा है?"
   }
  ],
  "index": "164",
  "roman": "lambe samay khade rehkar"
 },
 {
  "en": "Heavy physical work",
  "hi": "भारी शारीरिक काम",
  "used_by": [
   "personal.occupation_strain=heavy_physical"
  ],
  "asked": [
   {
    "qid": "personal.occupation_strain",
    "en": "What is your work like?",
    "hi": "आपका काम कैसा है?"
   }
  ],
  "index": "165",
  "roman": "bhaari shaaririk kaam"
 },
 {
  "en": "Night shifts",
  "hi": "रात की पाली",
  "used_by": [
   "personal.occupation_strain=night_shift"
  ],
  "asked": [
   {
    "qid": "personal.occupation_strain",
    "en": "What is your work like?",
    "hi": "आपका काम कैसा है?"
   }
  ],
  "index": "166",
  "roman": "raat ki paali"
 },
 {
  "en": "Not working at present",
  "hi": "अभी काम नहीं करते",
  "used_by": [
   "personal.occupation_strain=not_working"
  ],
  "asked": [
   {
    "qid": "personal.occupation_strain",
    "en": "What is your work like?",
    "hi": "आपका काम कैसा है?"
   }
  ],
  "index": "167",
  "roman": "abhi kaam nahin karte"
 },
 {
  "en": "Irregular",
  "hi": "अनियमित",
  "used_by": [
   "personal.menstrual=irregular"
  ],
  "asked": [
   {
    "qid": "personal.menstrual",
    "en": "How are your periods?",
    "hi": "आपकी माहवारी कैसी रहती है?"
   }
  ],
  "index": "168",
  "roman": "aniyamit"
 },
 {
  "en": "Painful",
  "hi": "दर्द भरी",
  "used_by": [
   "personal.menstrual=painful"
  ],
  "asked": [
   {
    "qid": "personal.menstrual",
    "en": "How are your periods?",
    "hi": "आपकी माहवारी कैसी रहती है?"
   }
  ],
  "index": "169",
  "roman": "dard bhari"
 },
 {
  "en": "Heavy bleeding",
  "hi": "ज़्यादा रक्तस्राव",
  "used_by": [
   "personal.menstrual=heavy"
  ],
  "asked": [
   {
    "qid": "personal.menstrual",
    "en": "How are your periods?",
    "hi": "आपकी माहवारी कैसी रहती है?"
   }
  ],
  "index": "170",
  "roman": "zyada raktsraav"
 },
 {
  "en": "They have stopped",
  "hi": "बंद हो गई है",
  "used_by": [
   "personal.menstrual=stopped"
  ],
  "asked": [
   {
    "qid": "personal.menstrual",
    "en": "How are your periods?",
    "hi": "आपकी माहवारी कैसी रहती है?"
   }
  ],
  "index": "171",
  "roman": "band ho gayi hai"
 },
 {
  "en": "I am thin, my skin is dry, I find it hard to sit still",
  "hi": "मैं दुबला-पतला हूँ, त्वचा रूखी है, एक जगह टिकना मुश्किल लगता है",
  "used_by": [
   "ayush.prakriti_screen=vata_lean_dry_restless"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "172",
  "roman": "main dubla-patla hoon, twacha rookhi hai, ek jagah tikna mushkil lagta hai"
 },
 {
  "en": "My appetite changes a lot from day to day",
  "hi": "मेरी भूख रोज़ बदलती रहती है",
  "used_by": [
   "ayush.prakriti_screen=vata_variable_appetite"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "173",
  "roman": "meri bhookh roz badalti rehti hai"
 },
 {
  "en": "I sleep lightly and wake easily",
  "hi": "मेरी नींद हल्की है, ज़रा सी आहट से खुल जाती है",
  "used_by": [
   "ayush.prakriti_screen=vata_light_sleep"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "174",
  "roman": "meri neend halki hai, zara si aahat se khul jaati hai"
 },
 {
  "en": "I get very hungry and cannot skip a meal",
  "hi": "मुझे तेज़ भूख लगती है, खाना छोड़ नहीं सकता",
  "used_by": [
   "ayush.prakriti_screen=pitta_sharp_appetite"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "175",
  "roman": "mujhe tez bhookh lagti hai, khaana chhod nahin sakta"
 },
 {
  "en": "I feel warm easily and cannot tolerate heat",
  "hi": "मुझे जल्दी गर्मी लगती है, गर्मी बर्दाश्त नहीं होती",
  "used_by": [
   "ayush.prakriti_screen=pitta_warm_intolerant"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "176",
  "roman": "mujhe jaldi garmi lagti hai, garmi bardaasht nahin hoti"
 },
 {
  "en": "I get irritated quickly",
  "hi": "मुझे जल्दी गुस्सा आ जाता है",
  "used_by": [
   "ayush.prakriti_screen=pitta_irritable"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "177",
  "roman": "mujhe jaldi gussa aa jaata hai"
 },
 {
  "en": "I have a heavy, solid build and gain weight easily",
  "hi": "मेरा शरीर भारी है, वज़न जल्दी बढ़ता है",
  "used_by": [
   "ayush.prakriti_screen=kapha_heavy_build"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "178",
  "roman": "mera shareer bhaari hai, wazan jaldi badhta hai"
 },
 {
  "en": "My digestion is slow and I feel heavy after eating",
  "hi": "मेरा पाचन धीमा है, खाने के बाद भारीपन लगता है",
  "used_by": [
   "ayush.prakriti_screen=kapha_slow_digestion"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "179",
  "roman": "mera paachan dheema hai, khaane ke baad bhaaripan lagta hai"
 },
 {
  "en": "I sleep deeply and for a long time",
  "hi": "मैं गहरी और लंबी नींद सोता हूँ",
  "used_by": [
   "ayush.prakriti_screen=kapha_deep_sleep"
  ],
  "asked": [
   {
    "qid": "ayush.prakriti_screen",
    "en": "Which of these sound like you, most of the time?",
    "hi": "इनमें से कौन सी बातें आप पर ज़्यादातर लागू होती हैं?"
   }
  ],
  "index": "180",
  "roman": "main gehri aur lambi neend sota hoon"
 },
 {
  "en": "More gas, dryness, restlessness or broken sleep than usual",
  "hi": "आम से ज़्यादा गैस, रूखापन, बेचैनी या टूटी नींद",
  "used_by": [
   "ayush.vikriti=vata_aggravated"
  ],
  "asked": [
   {
    "qid": "ayush.vikriti",
    "en": "And right now, which of these have changed for you recently?",
    "hi": "और अभी हाल में, इनमें से क्या बदला है?"
   }
  ],
  "index": "181",
  "roman": "aam se zyada gas, rookhaapan, bechaini ya tooti neend"
 },
 {
  "en": "More burning, acidity, heat or anger than usual",
  "hi": "आम से ज़्यादा जलन, अम्लता, गर्मी या गुस्सा",
  "used_by": [
   "ayush.vikriti=pitta_aggravated"
  ],
  "asked": [
   {
    "qid": "ayush.vikriti",
    "en": "And right now, which of these have changed for you recently?",
    "hi": "और अभी हाल में, इनमें से क्या बदला है?"
   }
  ],
  "index": "182",
  "roman": "aam se zyada jalan, amlata, garmi ya gussa"
 },
 {
  "en": "More heaviness, congestion, sluggishness or sweetness in the mouth",
  "hi": "आम से ज़्यादा भारीपन, कफ़, सुस्ती या मुँह में मिठास",
  "used_by": [
   "ayush.vikriti=kapha_aggravated"
  ],
  "asked": [
   {
    "qid": "ayush.vikriti",
    "en": "And right now, which of these have changed for you recently?",
    "hi": "और अभी हाल में, इनमें से क्या बदला है?"
   }
  ],
  "index": "183",
  "roman": "aam se zyada bhaaripan, kaf, susti ya munh mein mithaas"
 },
 {
  "en": "Nothing has changed particularly",
  "hi": "कुछ ख़ास नहीं बदला",
  "used_by": [
   "ayush.vikriti=unclear"
  ],
  "asked": [
   {
    "qid": "ayush.vikriti",
    "en": "And right now, which of these have changed for you recently?",
    "hi": "और अभी हाल में, इनमें से क्या बदला है?"
   }
  ],
  "index": "184",
  "roman": "kuch khaas nahin badla"
 },
 {
  "en": "Strong, I rarely fall ill",
  "hi": "मज़बूत, मैं कम ही बीमार पड़ता हूँ",
  "used_by": [
   "ayush.sara=pravara"
  ],
  "asked": [
   {
    "qid": "ayush.sara",
    "en": "In general, how strong and well-built do you feel your body is?",
    "hi": "आम तौर पर, आपको अपना शरीर कितना मज़बूत और गठा हुआ लगता है?"
   }
  ],
  "index": "185",
  "roman": "mazboot, main kam hi beemaar padta hoon"
 },
 {
  "en": "Average",
  "hi": "ठीक-ठाक",
  "used_by": [
   "ayush.sara=madhyama"
  ],
  "asked": [
   {
    "qid": "ayush.sara",
    "en": "In general, how strong and well-built do you feel your body is?",
    "hi": "आम तौर पर, आपको अपना शरीर कितना मज़बूत और गठा हुआ लगता है?"
   }
  ],
  "index": "186",
  "roman": "theek-thaak"
 },
 {
  "en": "Weak, I fall ill often",
  "hi": "कमज़ोर, मैं जल्दी बीमार पड़ता हूँ",
  "used_by": [
   "ayush.sara=avara"
  ],
  "asked": [
   {
    "qid": "ayush.sara",
    "en": "In general, how strong and well-built do you feel your body is?",
    "hi": "आम तौर पर, आपको अपना शरीर कितना मज़बूत और गठा हुआ लगता है?"
   }
  ],
  "index": "187",
  "roman": "kamzor, main jaldi beemaar padta hoon"
 },
 {
  "en": "I cannot say",
  "hi": "बता नहीं सकता",
  "used_by": [
   "ayush.sara=unassessed",
   "ayush.samhanana=unassessed",
   "ayush.pramana=unassessed",
   "ayush.satmya=unassessed",
   "ayush.sattva=unassessed"
  ],
  "asked": [
   {
    "qid": "ayush.sara",
    "en": "In general, how strong and well-built do you feel your body is?",
    "hi": "आम तौर पर, आपको अपना शरीर कितना मज़बूत और गठा हुआ लगता है?"
   },
   {
    "qid": "ayush.samhanana",
    "en": "How would you describe your body build?",
    "hi": "आप अपने शरीर की बनावट कैसी बताएँगे?"
   },
   {
    "qid": "ayush.pramana",
    "en": "Compared with others of your age and height, what is your body size?",
    "hi": "अपनी उम्र और क़द के दूसरे लोगों के मुक़ाबले, आपका शरीर कैसा है?"
   },
   {
    "qid": "ayush.satmya",
    "en": "When the weather changes, or your food or routine changes, how do you cope?",
    "hi": "जब मौसम बदलता है, या खाना-पीना और दिनचर्या बदलती है, तो आप कैसे झेलते हैं?"
   },
   {
    "qid": "ayush.sattva",
    "en": "When something difficult or painful happens, how do you usually hold up?",
    "hi": "जब कोई मुश्किल या तकलीफ़ आती है, तो आप आम तौर पर कैसे संभलते हैं?"
   }
  ],
  "index": "188",
  "roman": "bata nahin sakta"
 },
 {
  "en": "Compact and firm",
  "hi": "गठा हुआ और कसा हुआ",
  "used_by": [
   "ayush.samhanana=compact_strong"
  ],
  "asked": [
   {
    "qid": "ayush.samhanana",
    "en": "How would you describe your body build?",
    "hi": "आप अपने शरीर की बनावट कैसी बताएँगे?"
   }
  ],
  "index": "189",
  "roman": "gatha hua aur kasa hua"
 },
 {
  "en": "Medium",
  "hi": "मध्यम",
  "used_by": [
   "ayush.samhanana=moderate"
  ],
  "asked": [
   {
    "qid": "ayush.samhanana",
    "en": "How would you describe your body build?",
    "hi": "आप अपने शरीर की बनावट कैसी बताएँगे?"
   }
  ],
  "index": "190",
  "roman": "madhyam"
 },
 {
  "en": "Loose or slack",
  "hi": "ढीला",
  "used_by": [
   "ayush.samhanana=loose_weak"
  ],
  "asked": [
   {
    "qid": "ayush.samhanana",
    "en": "How would you describe your body build?",
    "hi": "आप अपने शरीर की बनावट कैसी बताएँगे?"
   }
  ],
  "index": "191",
  "roman": "dheela"
 },
 {
  "en": "About the same",
  "hi": "लगभग बराबर",
  "used_by": [
   "ayush.pramana=proportionate"
  ],
  "asked": [
   {
    "qid": "ayush.pramana",
    "en": "Compared with others of your age and height, what is your body size?",
    "hi": "अपनी उम्र और क़द के दूसरे लोगों के मुक़ाबले, आपका शरीर कैसा है?"
   }
  ],
  "index": "192",
  "roman": "lagbhag baraabar"
 },
 {
  "en": "Larger",
  "hi": "ज़्यादा भारी",
  "used_by": [
   "ayush.pramana=above_proportion"
  ],
  "asked": [
   {
    "qid": "ayush.pramana",
    "en": "Compared with others of your age and height, what is your body size?",
    "hi": "अपनी उम्र और क़द के दूसरे लोगों के मुक़ाबले, आपका शरीर कैसा है?"
   }
  ],
  "index": "193",
  "roman": "zyada bhaari"
 },
 {
  "en": "Smaller",
  "hi": "ज़्यादा दुबला",
  "used_by": [
   "ayush.pramana=below_proportion"
  ],
  "asked": [
   {
    "qid": "ayush.pramana",
    "en": "Compared with others of your age and height, what is your body size?",
    "hi": "अपनी उम्र और क़द के दूसरे लोगों के मुक़ाबले, आपका शरीर कैसा है?"
   }
  ],
  "index": "194",
  "roman": "zyada dubla"
 },
 {
  "en": "It does not bother me",
  "hi": "मुझे कोई फ़र्क़ नहीं पड़ता",
  "used_by": [
   "ayush.satmya=adapts_easily"
  ],
  "asked": [
   {
    "qid": "ayush.satmya",
    "en": "When the weather changes, or your food or routine changes, how do you cope?",
    "hi": "जब मौसम बदलता है, या खाना-पीना और दिनचर्या बदलती है, तो आप कैसे झेलते हैं?"
   }
  ],
  "index": "195",
  "roman": "mujhe koi farq nahin padta"
 },
 {
  "en": "It bothers me a little",
  "hi": "थोड़ा असर पड़ता है",
  "used_by": [
   "ayush.satmya=adapts_moderately"
  ],
  "asked": [
   {
    "qid": "ayush.satmya",
    "en": "When the weather changes, or your food or routine changes, how do you cope?",
    "hi": "जब मौसम बदलता है, या खाना-पीना और दिनचर्या बदलती है, तो आप कैसे झेलते हैं?"
   }
  ],
  "index": "196",
  "roman": "thoda asar padta hai"
 },
 {
  "en": "I fall ill whenever things change",
  "hi": "बदलाव होते ही मैं बीमार पड़ जाता हूँ",
  "used_by": [
   "ayush.satmya=adapts_poorly"
  ],
  "asked": [
   {
    "qid": "ayush.satmya",
    "en": "When the weather changes, or your food or routine changes, how do you cope?",
    "hi": "जब मौसम बदलता है, या खाना-पीना और दिनचर्या बदलती है, तो आप कैसे झेलते हैं?"
   }
  ],
  "index": "197",
  "roman": "badlaav hote hi main beemaar pad jaata hoon"
 },
 {
  "en": "I stay steady and carry on",
  "hi": "मैं शांत रहकर काम चलाता रहता हूँ",
  "used_by": [
   "ayush.sattva=pravara"
  ],
  "asked": [
   {
    "qid": "ayush.sattva",
    "en": "When something difficult or painful happens, how do you usually hold up?",
    "hi": "जब कोई मुश्किल या तकलीफ़ आती है, तो आप आम तौर पर कैसे संभलते हैं?"
   }
  ],
  "index": "198",
  "roman": "main shaant rehkar kaam chalaata rehta hoon"
 },
 {
  "en": "I manage, with some effort",
  "hi": "थोड़ी मेहनत से संभल जाता हूँ",
  "used_by": [
   "ayush.sattva=madhyama"
  ],
  "asked": [
   {
    "qid": "ayush.sattva",
    "en": "When something difficult or painful happens, how do you usually hold up?",
    "hi": "जब कोई मुश्किल या तकलीफ़ आती है, तो आप आम तौर पर कैसे संभलते हैं?"
   }
  ],
  "index": "199",
  "roman": "thodi mehnat se sambhal jaata hoon"
 },
 {
  "en": "I get shaken easily",
  "hi": "मैं जल्दी घबरा जाता हूँ",
  "used_by": [
   "ayush.sattva=avara"
  ],
  "asked": [
   {
    "qid": "ayush.sattva",
    "en": "When something difficult or painful happens, how do you usually hold up?",
    "hi": "जब कोई मुश्किल या तकलीफ़ आती है, तो आप आम तौर पर कैसे संभलते हैं?"
   }
  ],
  "index": "200",
  "roman": "main jaldi ghabra jaata hoon"
 },
 {
  "en": "I eat a full meal and it digests well",
  "hi": "मैं भरपेट खाता हूँ और वह अच्छे से पचता है",
  "used_by": [
   "ayush.ahara_shakti=good_intake_good_digestion"
  ],
  "asked": [
   {
    "qid": "ayush.ahara_shakti",
    "en": "How much can you eat, and how well does it digest?",
    "hi": "आप कितना खा पाते हैं, और वह कितना अच्छा पचता है?"
   }
  ],
  "index": "201",
  "roman": "main bharpet khaata hoon aur woh achchhe se pachta hai"
 },
 {
  "en": "I eat well but feel heavy or bloated after",
  "hi": "मैं अच्छा खाता हूँ पर बाद में भारीपन या गैस रहती है",
  "used_by": [
   "ayush.ahara_shakti=good_intake_poor_digestion"
  ],
  "asked": [
   {
    "qid": "ayush.ahara_shakti",
    "en": "How much can you eat, and how well does it digest?",
    "hi": "आप कितना खा पाते हैं, और वह कितना अच्छा पचता है?"
   }
  ],
  "index": "202",
  "roman": "main achchha khaata hoon par baad mein bhaaripan ya gas rehti hai"
 },
 {
  "en": "I eat little, but what I eat digests fine",
  "hi": "मैं कम खाता हूँ, पर जो खाता हूँ वह पच जाता है",
  "used_by": [
   "ayush.ahara_shakti=poor_intake_good_digestion"
  ],
  "asked": [
   {
    "qid": "ayush.ahara_shakti",
    "en": "How much can you eat, and how well does it digest?",
    "hi": "आप कितना खा पाते हैं, और वह कितना अच्छा पचता है?"
   }
  ],
  "index": "203",
  "roman": "main kam khaata hoon, par jo khaata hoon woh pach jaata hai"
 },
 {
  "en": "I eat little and it still does not digest",
  "hi": "मैं कम खाता हूँ और वह भी नहीं पचता",
  "used_by": [
   "ayush.ahara_shakti=poor_intake_poor_digestion"
  ],
  "asked": [
   {
    "qid": "ayush.ahara_shakti",
    "en": "How much can you eat, and how well does it digest?",
    "hi": "आप कितना खा पाते हैं, और वह कितना अच्छा पचता है?"
   }
  ],
  "index": "204",
  "roman": "main kam khaata hoon aur woh bhi nahin pachta"
 },
 {
  "en": "A lot, I do not tire easily",
  "hi": "बहुत, मैं जल्दी नहीं थकता",
  "used_by": [
   "ayush.vyayama_shakti=high"
  ],
  "asked": [
   {
    "qid": "ayush.vyayama_shakti",
    "en": "How much physical work can you do before you have to stop?",
    "hi": "आप रुकने से पहले कितना शारीरिक काम कर लेते हैं?"
   }
  ],
  "index": "205",
  "roman": "bahut, main jaldi nahin thakta"
 },
 {
  "en": "A normal amount",
  "hi": "सामान्य",
  "used_by": [
   "ayush.vyayama_shakti=moderate"
  ],
  "asked": [
   {
    "qid": "ayush.vyayama_shakti",
    "en": "How much physical work can you do before you have to stop?",
    "hi": "आप रुकने से पहले कितना शारीरिक काम कर लेते हैं?"
   }
  ],
  "index": "206",
  "roman": "saamaanya"
 },
 {
  "en": "I tire quickly",
  "hi": "मैं जल्दी थक जाता हूँ",
  "used_by": [
   "ayush.vyayama_shakti=low"
  ],
  "asked": [
   {
    "qid": "ayush.vyayama_shakti",
    "en": "How much physical work can you do before you have to stop?",
    "hi": "आप रुकने से पहले कितना शारीरिक काम कर लेते हैं?"
   }
  ],
  "index": "207",
  "roman": "main jaldi thak jaata hoon"
 },
 {
  "en": "I cannot do physical work at all",
  "hi": "मैं शारीरिक काम कर ही नहीं पाता",
  "used_by": [
   "ayush.vyayama_shakti=cannot_exert"
  ],
  "asked": [
   {
    "qid": "ayush.vyayama_shakti",
    "en": "How much physical work can you do before you have to stop?",
    "hi": "आप रुकने से पहले कितना शारीरिक काम कर लेते हैं?"
   }
  ],
  "index": "208",
  "roman": "main shaaririk kaam kar hi nahin paata"
 },
 {
  "en": "Steady — I get hungry at the usual times",
  "hi": "एक जैसी — समय पर भूख लगती है",
  "used_by": [
   "ayush.agni=sama"
  ],
  "asked": [
   {
    "qid": "ayush.agni",
    "en": "How is your hunger, day to day?",
    "hi": "आपकी भूख रोज़ कैसी रहती है?"
   }
  ],
  "index": "209",
  "roman": "ek jaisi - samay par bhookh lagti hai"
 },
 {
  "en": "Irregular — sometimes strong, sometimes none",
  "hi": "अनियमित — कभी तेज़, कभी बिल्कुल नहीं",
  "used_by": [
   "ayush.agni=vishama"
  ],
  "asked": [
   {
    "qid": "ayush.agni",
    "en": "How is your hunger, day to day?",
    "hi": "आपकी भूख रोज़ कैसी रहती है?"
   }
  ],
  "index": "210",
  "roman": "aniyamit - kabhi tez, kabhi bilkul nahin"
 },
 {
  "en": "Very strong — I feel hungry again soon after eating",
  "hi": "बहुत तेज़ — खाने के थोड़ी देर बाद फिर भूख लगती है",
  "used_by": [
   "ayush.agni=tikshna"
  ],
  "asked": [
   {
    "qid": "ayush.agni",
    "en": "How is your hunger, day to day?",
    "hi": "आपकी भूख रोज़ कैसी रहती है?"
   }
  ],
  "index": "211",
  "roman": "bahut tez - khaane ke thodi der baad phir bhookh lagti hai"
 },
 {
  "en": "Weak — I rarely feel hungry",
  "hi": "मंद — मुझे कम ही भूख लगती है",
  "used_by": [
   "ayush.agni=manda"
  ],
  "asked": [
   {
    "qid": "ayush.agni",
    "en": "How is your hunger, day to day?",
    "hi": "आपकी भूख रोज़ कैसी रहती है?"
   }
  ],
  "index": "212",
  "roman": "mand - mujhe kam hi bhookh lagti hai"
 },
 {
  "en": "Easily, sometimes more than once a day",
  "hi": "आसानी से, कभी-कभी दिन में एक से ज़्यादा बार",
  "used_by": [
   "ayush.koshtha=mridu"
  ],
  "asked": [
   {
    "qid": "ayush.koshtha",
    "en": "Do your bowels move easily, or do you need something to help?",
    "hi": "आपका पेट आसानी से साफ़ होता है, या कुछ लेना पड़ता है?"
   }
  ],
  "index": "213",
  "roman": "aasaani se, kabhi-kabhi din mein ek se zyada baar"
 },
 {
  "en": "Normally, once a day",
  "hi": "सामान्य, दिन में एक बार",
  "used_by": [
   "ayush.koshtha=madhya"
  ],
  "asked": [
   {
    "qid": "ayush.koshtha",
    "en": "Do your bowels move easily, or do you need something to help?",
    "hi": "आपका पेट आसानी से साफ़ होता है, या कुछ लेना पड़ता है?"
   }
  ],
  "index": "214",
  "roman": "saamaanya, din mein ek baar"
 },
 {
  "en": "With difficulty, I often need something",
  "hi": "मुश्किल से, अक्सर कुछ लेना पड़ता है",
  "used_by": [
   "ayush.koshtha=krura"
  ],
  "asked": [
   {
    "qid": "ayush.koshtha",
    "en": "Do your bowels move easily, or do you need something to help?",
    "hi": "आपका पेट आसानी से साफ़ होता है, या कुछ लेना पड़ता है?"
   }
  ],
  "index": "215",
  "roman": "mushkil se, aksar kuch lena padta hai"
 },
 {
  "en": "Yes, at fixed times",
  "hi": "हाँ, तय समय पर",
  "used_by": [
   "ahara.meal_regularity=regular_times"
  ],
  "asked": [
   {
    "qid": "ahara.meal_regularity",
    "en": "Do you eat at regular times?",
    "hi": "क्या आप तय समय पर खाना खाते हैं?"
   }
  ],
  "index": "216",
  "roman": "haan, tay samay par"
 },
 {
  "en": "At different times each day",
  "hi": "रोज़ अलग-अलग समय पर",
  "used_by": [
   "ahara.meal_regularity=irregular"
  ],
  "asked": [
   {
    "qid": "ahara.meal_regularity",
    "en": "Do you eat at regular times?",
    "hi": "क्या आप तय समय पर खाना खाते हैं?"
   }
  ],
  "index": "217",
  "roman": "roz alag-alag samay par"
 },
 {
  "en": "I often skip meals",
  "hi": "मैं अक्सर खाना छोड़ देता हूँ",
  "used_by": [
   "ahara.meal_regularity=skips_meals"
  ],
  "asked": [
   {
    "qid": "ahara.meal_regularity",
    "en": "Do you eat at regular times?",
    "hi": "क्या आप तय समय पर खाना खाते हैं?"
   }
  ],
  "index": "218",
  "roman": "main aksar khaana chhod deta hoon"
 },
 {
  "en": "Sweet — rice, milk, sugar",
  "hi": "मधुर — चावल, दूध, मीठा",
  "used_by": [
   "ahara.rasa_preference=madhura"
  ],
  "asked": [
   {
    "qid": "ahara.rasa_preference",
    "en": "Which tastes do you eat the most of?",
    "hi": "आप किस स्वाद का खाना सबसे ज़्यादा खाते हैं?"
   }
  ],
  "index": "219",
  "roman": "madhur - chaawal, doodh, meetha"
 },
 {
  "en": "Sour — curd, tamarind, lemon",
  "hi": "अम्ल — दही, इमली, नींबू",
  "used_by": [
   "ahara.rasa_preference=amla"
  ],
  "asked": [
   {
    "qid": "ahara.rasa_preference",
    "en": "Which tastes do you eat the most of?",
    "hi": "आप किस स्वाद का खाना सबसे ज़्यादा खाते हैं?"
   }
  ],
  "index": "220",
  "roman": "amla - dahi, imli, neembu"
 },
 {
  "en": "Salty — pickles, papad",
  "hi": "लवण — अचार, पापड़",
  "used_by": [
   "ahara.rasa_preference=lavana"
  ],
  "asked": [
   {
    "qid": "ahara.rasa_preference",
    "en": "Which tastes do you eat the most of?",
    "hi": "आप किस स्वाद का खाना सबसे ज़्यादा खाते हैं?"
   }
  ],
  "index": "221",
  "roman": "lavan - achaar, paapad"
 },
 {
  "en": "Pungent — chilli, pepper, ginger",
  "hi": "कटु — मिर्च, काली मिर्च, अदरक",
  "used_by": [
   "ahara.rasa_preference=katu"
  ],
  "asked": [
   {
    "qid": "ahara.rasa_preference",
    "en": "Which tastes do you eat the most of?",
    "hi": "आप किस स्वाद का खाना सबसे ज़्यादा खाते हैं?"
   }
  ],
  "index": "222",
  "roman": "katu - mirch, kaali mirch, adrak"
 },
 {
  "en": "Bitter — bitter gourd, fenugreek",
  "hi": "तिक्त — करेला, मेथी",
  "used_by": [
   "ahara.rasa_preference=tikta"
  ],
  "asked": [
   {
    "qid": "ahara.rasa_preference",
    "en": "Which tastes do you eat the most of?",
    "hi": "आप किस स्वाद का खाना सबसे ज़्यादा खाते हैं?"
   }
  ],
  "index": "223",
  "roman": "tikt - karela, methi"
 },
 {
  "en": "Astringent — pulses, banana, tea",
  "hi": "कषाय — दालें, केला, चाय",
  "used_by": [
   "ahara.rasa_preference=kashaya"
  ],
  "asked": [
   {
    "qid": "ahara.rasa_preference",
    "en": "Which tastes do you eat the most of?",
    "hi": "आप किस स्वाद का खाना सबसे ज़्यादा खाते हैं?"
   }
  ],
  "index": "224",
  "roman": "kashaay - daalein, kela, chaay"
 },
 {
  "en": "Less than four glasses",
  "hi": "चार गिलास से कम",
  "used_by": [
   "ahara.water_intake=low"
  ],
  "asked": [
   {
    "qid": "ahara.water_intake",
    "en": "How much water do you drink in a day?",
    "hi": "आप दिन में कितना पानी पीते हैं?"
   }
  ],
  "index": "225",
  "roman": "chaar gilaas se kam"
 },
 {
  "en": "Around six to eight glasses",
  "hi": "लगभग छह से आठ गिलास",
  "used_by": [
   "ahara.water_intake=moderate"
  ],
  "asked": [
   {
    "qid": "ahara.water_intake",
    "en": "How much water do you drink in a day?",
    "hi": "आप दिन में कितना पानी पीते हैं?"
   }
  ],
  "index": "226",
  "roman": "lagbhag chhah se aath gilaas"
 },
 {
  "en": "More than eight glasses",
  "hi": "आठ गिलास से ज़्यादा",
  "used_by": [
   "ahara.water_intake=high"
  ],
  "asked": [
   {
    "qid": "ahara.water_intake",
    "en": "How much water do you drink in a day?",
    "hi": "आप दिन में कितना पानी पीते हैं?"
   }
  ],
  "index": "227",
  "roman": "aath gilaas se zyada"
 },
 {
  "en": "Hardly at all",
  "hi": "बहुत कम",
  "used_by": [
   "vihara.activity=sedentary"
  ],
  "asked": [
   {
    "qid": "vihara.activity",
    "en": "How much do you move about in a normal day?",
    "hi": "आम दिन में आप कितना चलते-फिरते हैं?"
   }
  ],
  "index": "228",
  "roman": "bahut kam"
 },
 {
  "en": "A little walking",
  "hi": "थोड़ा चलना-फिरना",
  "used_by": [
   "vihara.activity=light"
  ],
  "asked": [
   {
    "qid": "vihara.activity",
    "en": "How much do you move about in a normal day?",
    "hi": "आम दिन में आप कितना चलते-फिरते हैं?"
   }
  ],
  "index": "229",
  "roman": "thoda chalna-phirna"
 },
 {
  "en": "A fair amount",
  "hi": "ठीक-ठाक",
  "used_by": [
   "vihara.activity=moderate"
  ],
  "asked": [
   {
    "qid": "vihara.activity",
    "en": "How much do you move about in a normal day?",
    "hi": "आम दिन में आप कितना चलते-फिरते हैं?"
   }
  ],
  "index": "230",
  "roman": "theek-thaak"
 },
 {
  "en": "Hard physical work every day",
  "hi": "रोज़ भारी शारीरिक काम",
  "used_by": [
   "vihara.activity=heavy"
  ],
  "asked": [
   {
    "qid": "vihara.activity",
    "en": "How much do you move about in a normal day?",
    "hi": "आम दिन में आप कितना चलते-फिरते हैं?"
   }
  ],
  "index": "231",
  "roman": "roz bhaari shaaririk kaam"
 },
 {
  "en": "Early at night, up early",
  "hi": "जल्दी सोना, जल्दी उठना",
  "used_by": [
   "vihara.sleep_pattern=early_to_bed"
  ],
  "asked": [
   {
    "qid": "vihara.sleep_pattern",
    "en": "When do you usually sleep?",
    "hi": "आप आम तौर पर कब सोते हैं?"
   }
  ],
  "index": "232",
  "roman": "jaldi sona, jaldi uthna"
 },
 {
  "en": "Late at night",
  "hi": "देर रात को",
  "used_by": [
   "vihara.sleep_pattern=late_night"
  ],
  "asked": [
   {
    "qid": "vihara.sleep_pattern",
    "en": "When do you usually sleep?",
    "hi": "आप आम तौर पर कब सोते हैं?"
   }
  ],
  "index": "233",
  "roman": "der raat ko"
 },
 {
  "en": "I also sleep during the day",
  "hi": "मैं दिन में भी सोता हूँ",
  "used_by": [
   "vihara.sleep_pattern=day_sleeping"
  ],
  "asked": [
   {
    "qid": "vihara.sleep_pattern",
    "en": "When do you usually sleep?",
    "hi": "आप आम तौर पर कब सोते हैं?"
   }
  ],
  "index": "234",
  "roman": "main din mein bhi sota hoon"
 },
 {
  "en": "No fixed time",
  "hi": "कोई तय समय नहीं",
  "used_by": [
   "vihara.sleep_pattern=irregular"
  ],
  "asked": [
   {
    "qid": "vihara.sleep_pattern",
    "en": "When do you usually sleep?",
    "hi": "आप आम तौर पर कब सोते हैं?"
   }
  ],
  "index": "235",
  "roman": "koi tay samay nahin"
 },
 {
  "en": "Sudden weakness in an arm or leg",
  "hi": "हाथ या पैर में अचानक कमज़ोरी",
  "used_by": [
   "ros.danger_signs=weakness_limb"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   }
  ],
  "index": "236",
  "roman": "haath ya pair mein achaanak kamzori"
 },
 {
  "en": "Sudden change in eyesight",
  "hi": "नज़र में अचानक बदलाव",
  "used_by": [
   "ros.danger_signs=vision_change"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   }
  ],
  "index": "237",
  "roman": "nazar mein achaanak badlaav"
 },
 {
  "en": "Fits",
  "hi": "दौरे",
  "used_by": [
   "ros.danger_signs=fits",
   "ros.neuro=fits"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "238",
  "roman": "daure"
 },
 {
  "en": "Fainting",
  "hi": "बेहोशी",
  "used_by": [
   "ros.danger_signs=fainting",
   "ros.neuro=fainting"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "239",
  "roman": "behoshi"
 },
 {
  "en": "Blood when coughing",
  "hi": "खाँसी में ख़ून",
  "used_by": [
   "ros.danger_signs=blood_in_sputum",
   "ros.cardioresp=blood_in_sputum"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.cardioresp",
    "en": "Any trouble with your chest, breathing or heart?",
    "hi": "छाती, साँस या दिल से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "240",
  "roman": "khaansi mein khoon"
 },
 {
  "en": "Blood in stool",
  "hi": "शौच में ख़ून",
  "used_by": [
   "ros.danger_signs=blood_in_stool",
   "ros.gi=blood_in_stool"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.gi",
    "en": "Any trouble with your stomach or digestion?",
    "hi": "पेट या पाचन से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "241",
  "roman": "shauch mein khoon"
 },
 {
  "en": "Black stool",
  "hi": "काला शौच",
  "used_by": [
   "ros.danger_signs=black_stool",
   "ros.gi=black_stool"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.gi",
    "en": "Any trouble with your stomach or digestion?",
    "hi": "पेट या पाचन से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "242",
  "roman": "kaala shauch"
 },
 {
  "en": "Blood in urine",
  "hi": "पेशाब में ख़ून",
  "used_by": [
   "ros.danger_signs=blood_in_urine",
   "ros.uro=blood_in_urine"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.uro",
    "en": "Any trouble passing urine?",
    "hi": "पेशाब से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "243",
  "roman": "peshaab mein khoon"
 },
 {
  "en": "Not able to pass urine",
  "hi": "पेशाब न आना",
  "used_by": [
   "ros.danger_signs=retention",
   "ros.uro=retention"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.uro",
    "en": "Any trouble passing urine?",
    "hi": "पेशाब से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "244",
  "roman": "peshaab na aana"
 },
 {
  "en": "Yellow eyes or skin",
  "hi": "आँखों या त्वचा का पीलापन",
  "used_by": [
   "ros.danger_signs=jaundice",
   "ros.gi=jaundice"
  ],
  "asked": [
   {
    "qid": "ros.danger_signs",
    "en": "Have you had any of these, even once?",
    "hi": "क्या आपको इनमें से कुछ हुआ है, एक बार भी?"
   },
   {
    "qid": "ros.gi",
    "en": "Any trouble with your stomach or digestion?",
    "hi": "पेट या पाचन से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "245",
  "roman": "aankhon ya twacha ka peelaapan"
 },
 {
  "en": "Losing weight without trying",
  "hi": "बिना कोशिश के वज़न घटना",
  "used_by": [
   "ros.general=weight_loss"
  ],
  "asked": [
   {
    "qid": "ros.general",
    "en": "Apart from all that, have you noticed any of these?",
    "hi": "इसके अलावा, क्या आपने इनमें से कुछ महसूस किया है?"
   }
  ],
  "index": "246",
  "roman": "bina koshish ke wazan ghatna"
 },
 {
  "en": "Gaining weight",
  "hi": "वज़न बढ़ना",
  "used_by": [
   "ros.general=weight_gain"
  ],
  "asked": [
   {
    "qid": "ros.general",
    "en": "Apart from all that, have you noticed any of these?",
    "hi": "इसके अलावा, क्या आपने इनमें से कुछ महसूस किया है?"
   }
  ],
  "index": "247",
  "roman": "wazan badhna"
 },
 {
  "en": "Sweating at night",
  "hi": "रात में पसीना",
  "used_by": [
   "ros.general=night_sweats"
  ],
  "asked": [
   {
    "qid": "ros.general",
    "en": "Apart from all that, have you noticed any of these?",
    "hi": "इसके अलावा, क्या आपने इनमें से कुछ महसूस किया है?"
   }
  ],
  "index": "248",
  "roman": "raat mein paseena"
 },
 {
  "en": "Feeling very tired",
  "hi": "बहुत थकान",
  "used_by": [
   "ros.general=fatigue"
  ],
  "asked": [
   {
    "qid": "ros.general",
    "en": "Apart from all that, have you noticed any of these?",
    "hi": "इसके अलावा, क्या आपने इनमें से कुछ महसूस किया है?"
   }
  ],
  "index": "249",
  "roman": "bahut thakaan"
 },
 {
  "en": "Getting breathless",
  "hi": "साँस फूलना",
  "used_by": [
   "ros.cardioresp=breathlessness"
  ],
  "asked": [
   {
    "qid": "ros.cardioresp",
    "en": "Any trouble with your chest, breathing or heart?",
    "hi": "छाती, साँस या दिल से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "250",
  "roman": "saans phoolna"
 },
 {
  "en": "Swollen feet or ankles",
  "hi": "पैरों या टख़नों में सूजन",
  "used_by": [
   "ros.cardioresp=ankle_swelling"
  ],
  "asked": [
   {
    "qid": "ros.cardioresp",
    "en": "Any trouble with your chest, breathing or heart?",
    "hi": "छाती, साँस या दिल से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "251",
  "roman": "pairon ya takhnon mein soojan"
 },
 {
  "en": "Trouble swallowing",
  "hi": "निगलने में तकलीफ़",
  "used_by": [
   "ros.gi=difficulty_swallowing"
  ],
  "asked": [
   {
    "qid": "ros.gi",
    "en": "Any trouble with your stomach or digestion?",
    "hi": "पेट या पाचन से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "252",
  "roman": "nigalne mein takleef"
 },
 {
  "en": "Numbness or tingling",
  "hi": "सुन्नपन या झनझनाहट",
  "used_by": [
   "ros.neuro=numbness"
  ],
  "asked": [
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "253",
  "roman": "sunnapan ya jhanjhanaahat"
 },
 {
  "en": "Weakness in an arm or leg",
  "hi": "हाथ या पैर में कमज़ोरी",
  "used_by": [
   "ros.neuro=weakness_limb"
  ],
  "asked": [
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "254",
  "roman": "haath ya pair mein kamzori"
 },
 {
  "en": "Change in eyesight",
  "hi": "नज़र में बदलाव",
  "used_by": [
   "ros.neuro=vision_change"
  ],
  "asked": [
   {
    "qid": "ros.neuro",
    "en": "Any trouble with your head, senses or nerves?",
    "hi": "सिर, इंद्रियों या नसों से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "255",
  "roman": "nazar mein badlaav"
 },
 {
  "en": "Burning",
  "hi": "जलन",
  "used_by": [
   "ros.uro=burning_urine"
  ],
  "asked": [
   {
    "qid": "ros.uro",
    "en": "Any trouble passing urine?",
    "hi": "पेशाब से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "256",
  "roman": "jalan"
 },
 {
  "en": "Going very often",
  "hi": "बार-बार जाना",
  "used_by": [
   "ros.uro=frequency"
  ],
  "asked": [
   {
    "qid": "ros.uro",
    "en": "Any trouble passing urine?",
    "hi": "पेशाब से जुड़ी कोई तकलीफ़?"
   }
  ],
  "index": "257",
  "roman": "baar-baar jaana"
 },
 {
  "en": "Yes, I have papers",
  "hi": "हाँ, मेरे पास काग़ज़ हैं",
  "used_by": [
   "docs.has_papers=True"
  ],
  "asked": [
   {
    "qid": "docs.has_papers",
    "en": "Do you have any old prescriptions, test reports or hospital papers with you?",
    "hi": "क्या आपके पास कोई पुराना पर्चा, जाँच रिपोर्ट या अस्पताल के काग़ज़ हैं?"
   }
  ],
  "index": "258",
  "roman": "haan, mere paas kaagaz hain"
 },
 {
  "en": "No, I do not",
  "hi": "नहीं, मेरे पास नहीं हैं",
  "used_by": [
   "docs.has_papers=False"
  ],
  "asked": [
   {
    "qid": "docs.has_papers",
    "en": "Do you have any old prescriptions, test reports or hospital papers with you?",
    "hi": "क्या आपके पास कोई पुराना पर्चा, जाँच रिपोर्ट या अस्पताल के काग़ज़ हैं?"
   }
  ],
  "index": "259",
  "roman": "nahin, mere paas nahin hain"
 },
 {
  "en": "zero",
  "hi": "शून्य",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "260",
  "roman": "shoonya"
 },
 {
  "en": "one",
  "hi": "एक",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "261",
  "roman": "ek"
 },
 {
  "en": "two",
  "hi": "दो",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "262",
  "roman": "do"
 },
 {
  "en": "three",
  "hi": "तीन",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "263",
  "roman": "teen"
 },
 {
  "en": "four",
  "hi": "चार",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "264",
  "roman": "chaar"
 },
 {
  "en": "five",
  "hi": "पाँच",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "265",
  "roman": "paanch"
 },
 {
  "en": "six",
  "hi": "छह",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "266",
  "roman": "chhah"
 },
 {
  "en": "seven",
  "hi": "सात",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "267",
  "roman": "saat"
 },
 {
  "en": "eight",
  "hi": "आठ",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "268",
  "roman": "aath"
 },
 {
  "en": "nine",
  "hi": "नौ",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "269",
  "roman": "nau"
 },
 {
  "en": "ten",
  "hi": "दस",
  "used_by": [
   "number"
  ],
  "asked": [
   {
    "qid": "number",
    "en": "Say just the number, on its own.",
    "hi": "सिर्फ़ संख्या बोलिए।"
   }
  ],
  "index": "270",
  "roman": "das"
 }
];
